name: Release charts
on:
#  push:
#    branches:
#      - master
#    paths:
#      - 'charts/**'
  schedule:
    # every friday at 4 o'clock
    - cron: '0 16 * * 5'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  bump-versions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Bump Keycloak
      uses: ./.github/actions/bumpVersionAction
      with:
        chart: keycloak

    - name: Bump Keycloak.X
      uses: ./.github/actions/bumpVersionAction
      with:
        chart: keycloakx

    - name: Bump Mailhog
      uses: ./.github/actions/bumpVersionAction
      with:
        chart: mailhog

    - name: Push Results
      id: pushResults
      run: |
        if git merge-base --is-ancestor HEAD @{u} ; then
          echo "publish=false" >> $GITHUB_OUTPUT
          echo "No push necesarry"
        else
          echo "Version bumps happened. Pushing now..."
          git push
          echo "publish=true" >> $GITHUB_OUTPUT
        fi
    outputs:
      publish: ${{ steps.pushResults.outputs.publish }}
